### ISSUE TITLE
KeyError: "Couldn't find enum google.protobuf.MethodOptions.IdempotencyLevel"

### ISSUE THREAD

**Issue by TheN1ghtmare** [tomer8007/kik-bot-api-unofficial#107]
Hi, I'm getting this error when I try to run any of the example scripts.

```
Traceback (most recent call last):
  File "interactive_client.py", line 5, in <module>
    from kik_unofficial.client import KikClient
  File "/media/user/4143-B8D1/kik-bot-api-unofficial/kik_unofficial/client.py", line 9, in <module>
    import kik_unofficial.callbacks as callbacks
  File "/media/user/4143-B8D1/kik-bot-api-unofficial/kik_unofficial/callbacks.py", line 2, in <module>
    from kik_unofficial.datatypes.xmpp.chatting import IncomingMessageDeliveredEvent, IncomingMessageReadEvent, IncomingChatMessage, \
  File "/media/user/4143-B8D1/kik-bot-api-unofficial/kik_unofficial/datatypes/xmpp/chatting.py", line 8, in <module>
    from kik_unofficial.datatypes.peers import Group
  File "/media/user/4143-B8D1/kik-bot-api-unofficial/kik_unofficial/datatypes/peers.py", line 6, in <module>
    from kik_unofficial.protobuf.entity.v1.entity_common_pb2 import EntityUser
  File "/media/user/4143-B8D1/kik-bot-api-unofficial/kik_unofficial/protobuf/entity/v1/entity_common_pb2.py", line 16, in <module>
    import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
  File "/media/user/4143-B8D1/kik-bot-api-unofficial/kik_unofficial/protobuf/protobuf_validation_pb2.py", line 16, in <module>
    from kik_unofficial.protobuf.google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
  File "/media/user/4143-B8D1/kik-bot-api-unofficial/kik_unofficial/protobuf/google/protobuf/descriptor_pb2.py", line 239, in <module>
    serialized_end=4762,
  File "/usr/lib/python3/dist-packages/google/protobuf/descriptor.py", line 602, in __new__
    return _message.default_pool.FindEnumTypeByName(full_name)
KeyError: "Couldn't find enum google.protobuf.MethodOptions.IdempotencyLevel"
```

**Comment by tomer8007** [comment]
I think you have an outdated/wrong version of the protbuf package. Please take a look at threads with the same problem [like here](https://github.com/tensorflow/tensorflow/issues/13533). I'm using protobuf version 3.6.1 and it's working fine for me. What version do you use?
