### ISSUE TITLE
Install failed / Command "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by ShadowGER** [tomer8007/kik-bot-api-unofficial#111]
Hello.
I set up a ubuntu 17.04 server. 
But i got this error message:
```
# pip3 install ./kik-bot-api-unofficial
Processing ./kik-bot-api-unofficial
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-09_n9gtc-build/setup.py", line 8, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-09_n9gtc-build/README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-09_n9gtc-build/

```
Tried:
```
sudo apt-get install python3.6.
sudo apt-get install python-pip
apt install python3-pip
pip install pyrebase
sudo apt-get install python3-pip
python get-pip.py 
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
sudo -H pip3 install gitsome
```
Still the same.

Python version:
```
python3 -V
Python 3.6.7
```
Any ideas what should be missing?

**Comment by tomer8007** [comment]
Whoops, that was because I removed the file `README.rst` recently. I've fixed the `setup.py` now. Please re-clone and tell me if it works.

**Comment by ShadowGER** [comment]
Yes. Now it workes. Thank you. :-)
