### ISSUE TITLE
Error when trying to login on Termux

### ISSUE THREAD

**Issue by Sitiaro** [tomer8007/kik-bot-api-unofficial#191]
I tried cloning and using the repo on Termux, installed lxml and pillow dependencies too but this error popped up after I entered my login details. Am I doing something wrong?
I'm using python 3.9.2 btw.

[2021-04-12 18:43:40,622] INFO   (thread Kik Connection): [+] Initiating the Kik Connection thread and connecting to kik server...                                                              Exception in thread Kik Connection:                             Traceback (most recent call last):                                File "/data/data/com.termux/files/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner                                  self.run()                                                    File "/data/data/com.termux/files/usr/lib/python3.9/threading.py", line 892, in run                                               self._target(*self._args, **self._kwargs)                     File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/kik_unofficial/client.py", line 639, in _kik_connection_thread_function                                                         self.loop.run_until_complete(connection_coroutine)            File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete                      return future.result()                                        File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 1017, in create_connection                      infos = await self._ensure_resolved(                          File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved                       return await loop.getaddrinfo(host, port, family=family, type=type,                                                           File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo                             return await self.run_in_executor(                            File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 809, in run_in_executor                         executor = concurrent.futures.ThreadPoolExecutor(             File "/data/data/com.termux/files/usr/lib/python3.9/concurrent/futures/__init__.py", line 49, in __getattr__                      from .thread import ThreadPoolExecutor as te                  File "/data/data/com.termux/files/usr/lib/python3.9/concurrent/futures/thread.py", line 37, in <module>                           threading._register_atexit(_python_exit)                      File "/data/data/com.termux/files/usr/lib/python3.9/threading.py", line 1374, in _register_atexit                                 raise RuntimeError("can't register atexit after shutdown")  RuntimeError: can't register atexit after shutdown

**Comment by tomer8007** [comment]
This is not a Termux problem, bur rather a known problem with Python 3.9+, the relevant issue is #172.

**Comment by Sitiaro** [comment]
Fixed the issue, had to get an older version of python and it worked.
For those of you who might face this problem in the near future;
(Termux)
Uninstall python -
$ pkg uninstall python

Check the arch of your device cpu using - 
$ uname -m

Go to https://github.com/Termux-pod/termux-pod and find the file corresponding to your device's CPU. According to @kcubeterm, you should try python_3.8.6_.deb first and then the static version if there is any error.

Download the raw .deb file in termux using web-get.

make sure you add ?raw=true to the end of the url, or else you'll end up downloading the html file. So it'll be something like this - 

$ wget https://github.com/Termux-pod/termux-pod/blob/main/arm/python/python_3.8.6_<CPU_ARCH.>.deb?raw=true

(replace <CPU_ARCH.> with your device's cpu)

Finally, execute the following command in termux - 
$ dpkg -i ./python_3.8.6_<CPU_ARCH.>.deb

Once again, replacing <CPU_ARCH.> with your cpu's architecture (for me it was arm).

Hope this answer helped you to install Python 3.8 and made the login thingie work for you.
