### ISSUE TITLE
New problem Kik server returned empty response

### ISSUE THREAD

**Issue by edroot** [tomer8007/kik-bot-api-unofficial#38]
Kik server returned empty response

**Comment by tomer8007** [comment]
Where do you get this error? What are you trying to do?

**Comment by edroot** [comment]
[+] Establishing session...
[+] Session established.
[+] Getting roster (chat partners list)...
Traceback (most recent call last):
  File "/home/vmsssd/kik-app-v3.1/examples/send_message.py", line 29, in <module>
    main()
  File "/home/vmsssd/kik-app-v3.1/examples/send_message.py", line 11, in main
    chat_partners = kik_client.get_chat_partners()
  File "/home/vmsssd/kik-app-v3.1/kik_unofficial/kikclient.py", line 190, in get_chat_partners
    self._make_request(data)
  File "/home/vmsssd/kik-app-v3.1/kik_unofficial/kikclient.py", line 753, in _make_request
    response = self._get_response()
  File "/home/vmsssd/kik-app-v3.1/kik_unofficial/kikclient.py", line 759, in _get_response
    raise KikEmptyResponseException(response, "Kik server returned empty response")
kik_unofficial.kik_exceptions.KikEmptyResponseException: Kik server returned empty response

**Comment by tomer8007** [comment]
Did you try using the new branch?
