### ISSUE TITLE
Kicking someone from group results in an error

### ISSUE THREAD

**Issue by rmcc3** [tomer8007/kik-bot-api-unofficial#65]
This error only happens after removing someone from a group. The error happens regardless of who does the kick.

`ERROR  (thread Kik Connection): Exception in callback KikClient._on_new_data_received(b'<iq type="e...</error></iq>')
handle: <Handle KikClient._on_new_data_received(b'<iq type="e...</error></iq>')>`

`Traceback (most recent call last):
  File "C:\Users\RM\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\RM\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kik_unofficial\client.py", line 245, in _on_new_data_received
    self._handle_received_iq_element(xml_element)
  File "C:\Users\RM\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kik_unofficial\client.py", line 279, in _handle_received_iq_element
    self._handle_xmlns(iq_element.query['xmlns'], iq_element)
  File "C:\Users\RM\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kik_unofficial\client.py", line 307, in _handle_xmlns
    raise NotImplementedError
NotImplementedError`

**Comment by tomer8007** [comment]
What's the exception?

**Comment by rmcc3** [comment]
Updated first comment

**Comment by tomer8007** [comment]
Thanks for letting me know. 
I commited a change that logs the unknown XML namespace you got. Now there won't be an exception (only a log). You can enable DEBUG logs to see if the data that was received is important/worth parsing.

**Comment by rmcc3** [comment]
Thanks! Using this to help me learn Python. Kinda just diving right in here :)
