### ISSUE TITLE
Receiving a GIF results in an NotImplementedError (crashes after so many errors)

### ISSUE THREAD

**Issue by rmcc3** [tomer8007/kik-bot-api-unofficial#67]
`[2018-08-14 16:35:38,724] ERROR  (thread Kik Connection): Exception in callback KikClient._on_new_data_received(b'<message fr..."/></message>')
handle: <Handle KikClient._on_new_data_received(b'<message fr..."/></message>')>
Traceback (most recent call last):
  File "C:\Users\RM\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\RM\Desktop\kik-bot-api-unofficial-new\kik_unofficial\client.py", line 247, in _on_new_data_received
    self._handle_xmpp_message(xml_element)
  File "C:\Users\RM\Desktop\kik-bot-api-unofficial-new\kik_unofficial\client.py", line 291, in _handle_xmpp_message
    self.callback.on_group_receipts_received(chatting.IncomingGroupReceiptsEvent(xmpp_message))
  File "C:\Users\RM\Desktop\kik-bot-api-unofficial-new\kik_unofficial\datatypes\xmpp\chatting.py", line 215, in __init__
    self.group_jid = data.g['jid']
TypeError: 'NoneType' object is not subscriptable
[2018-08-14 16:35:38,744] ERROR  (thread Kik Connection): Exception in callback KikClient._on_new_data_received(b'<message fr...sg></message>')
handle: <Handle KikClient._on_new_data_received(b'<message fr...sg></message>')>
Traceback (most recent call last):
  File "C:\Users\RM\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\RM\Desktop\kik-bot-api-unofficial-new\kik_unofficial\client.py", line 247, in _on_new_data_received
    self._handle_xmpp_message(xml_element)
  File "C:\Users\RM\Desktop\kik-bot-api-unofficial-new\kik_unofficial\client.py", line 294, in _handle_xmpp_message
    self.xml_namespace_handlers['jabber:client'].handle(xmpp_message)
  File "C:\Users\RM\Desktop\kik-bot-api-unofficial-new\kik_unofficial\xmlns_handlers.py", line 82, in handle
    raise NotImplementedError
NotImplementedError`

**Comment by tomer8007** [comment]
Thank you for this report.
In order to support these GIF messages I need you to post the received data (in its XML form) by allowing DEBUG logs.
