### ISSUE TITLE
SSL failure executing examples 

### ISSUE THREAD

**Issue by ApparentlyImDumb** [tomer8007/kik-bot-api-unofficial#97]
Hi I'm failing at the first hurdle when trying the examples.

Using python 3.6.5 I get an SSL failure.

python3 --version && python3 ./interactive_client.py 
Python 3.6.5
[2018-12-29 19:58:16,935] INFO   (thread Kik Connection): [+] Initiating the Kik Connection thread and connecting to kik server...
Exception in thread Kik Connection:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kik_unofficial/client.py", line 376, in _kik_connection_thread_function
    self.loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 804, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 830, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

**Comment by tomer8007** [comment]
I think [this answer](https://stackoverflow.com/a/41692664/1806873) is your solution, given the fact you appear to be on MacOS.
